# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-14 04:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bettingbot',
            name='is_cheating',
            field=models.BooleanField(default=False, verbose_name='Cheating'),
        ),
    ]
