# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-16 03:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpost',
            name='give',
        ),
        migrations.RemoveField(
            model_name='userpost',
            name='steamer',
        ),
        migrations.AlterModelOptions(
            name='storerecord',
            options={'verbose_name': 'Store Record', 'verbose_name_plural': 'Store Record'},
        ),
        migrations.DeleteModel(
            name='GiveAway',
        ),
        migrations.DeleteModel(
            name='UserPost',
        ),
    ]
