# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-30 07:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='steamrobotapiitem',
            name='item_refer_igxe_price',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='steamrobotapiitem',
            name='item_refer_igxe_steam_price',
            field=models.FloatField(null=True),
        ),
    ]
