# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-28 08:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coinflipgame',
            name='win_ticket',
            field=models.BigIntegerField(default=-1, verbose_name='Win Ticket'),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='tickets_begin',
            field=models.BigIntegerField(default=-1, verbose_name='Ticket Begin'),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='tickets_end',
            field=models.BigIntegerField(default=-1, verbose_name='Ticket End'),
        ),
        migrations.AlterField(
            model_name='propitem',
            name='send_record',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='betting.SendRecord', verbose_name='Send Record'),
        ),
    ]
