# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-16 08:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('betting', '0002_auto_20171016_1129'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAmountRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(editable=False, max_length=63, unique=True, verbose_name='UID')),
                ('create_time', models.DateTimeField(editable=False, verbose_name='Create Time')),
                ('update_time', models.DateTimeField(editable=False, verbose_name='Update Time')),
                ('amount', models.FloatField(default=0.0, verbose_name='Amount')),
                ('total_amount', models.FloatField(default=0.0, verbose_name='Total Amount')),
                ('reason', models.CharField(blank=True, default=None, max_length=256, null=True, verbose_name='Reason')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amount_records', to='betting.CoinFlipGame', verbose_name='Game')),
                ('steamer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amount_records', to=settings.AUTH_USER_MODEL, verbose_name='Steamer')),
            ],
            options={
                'verbose_name': 'UserAmountReocrds',
                'verbose_name_plural': 'UserAmountReocrds',
            },
        ),
    ]
