# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-28 10:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0002_auto_20171128_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendrecord',
            name='game',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='betting.CoinFlipGame', verbose_name='Game'),
        ),
    ]
