# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-22 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0003_useramountrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiveAway',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(editable=False, max_length=63, unique=True, verbose_name='UID')),
                ('create_time', models.DateTimeField(editable=False, verbose_name='Create Time')),
                ('update_time', models.DateTimeField(editable=False, verbose_name='Update Time')),
                ('title', models.CharField(max_length=128, verbose_name='Title')),
                ('img', models.URLField(verbose_name='Img Url')),
                ('href', models.URLField(verbose_name='Target Url')),
                ('button', models.CharField(max_length=64, verbose_name='Button')),
                ('num', models.IntegerField(default=1, verbose_name='Num.')),
                ('enable', models.BooleanField(default=True, verbose_name='Enable')),
                ('remark', models.CharField(max_length=64, verbose_name='Remark')),
            ],
            options={
                'verbose_name': 'Give Away',
                'verbose_name_plural': 'Give Away',
            },
        ),
        migrations.AlterField(
            model_name='announcement',
            name='page_type',
            field=models.SmallIntegerField(choices=[(0, 'Coinflip'), (1, 'Jackpot'), (5, 'All pages')], default=0, verbose_name='Page Type'),
        ),
        migrations.AlterField(
            model_name='coinflipgame',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Initial'), (2, 'Joinable'), (3, 'Joining'), (4, 'Full'), (5, 'Running'), (6, 'Cancelled'), (11, 'End')], default=0, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='team',
            field=models.IntegerField(choices=[(0, 'T'), (1, 'CT')], default=0, verbose_name='Team'),
        ),
        migrations.AlterField(
            model_name='useramountrecord',
            name='amount',
            field=models.FloatField(default=0.0, verbose_name='Profit'),
        ),
        migrations.AlterField(
            model_name='useramountrecord',
            name='total_amount',
            field=models.FloatField(default=0.0, verbose_name='Total Profit'),
        ),
    ]
