# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-27 06:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0004_auto_20171022_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propitem',
            name='market_hash_name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Market Hash Name'),
        ),
        migrations.AlterField(
            model_name='propitem',
            name='owner',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to=settings.AUTH_USER_MODEL, verbose_name='owner'),
        ),
    ]
