# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-27 06:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='steamuser',
            options={'verbose_name': 'SteamUsers', 'verbose_name_plural': 'SteamUsers'},
        ),
        migrations.AddField(
            model_name='steamuser',
            name='amount',
            field=models.FloatField(default=0.0, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='steamuser',
            name='can_chat',
            field=models.BooleanField(default=True, verbose_name='Can Chat'),
        ),
        migrations.AlterField(
            model_name='steamuser',
            name='is_cheating',
            field=models.BooleanField(default=False, verbose_name='Cheating'),
        ),
        migrations.AlterField(
            model_name='steamuser',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Is Staff'),
        ),
        migrations.AlterField(
            model_name='steamuser',
            name='tradeurl',
            field=models.CharField(blank=True, default=None, max_length=300, null=True),
        ),
    ]
